version: '3.9'
services:
  mysql-server:
    profiles: ["cluster", "db", "mysql-db"]
    extends:
      file: mysql-server/docker-compose.yml
      service: mysql-server
    networks:
      - backend

  greenplum-db-6:
    profiles: ["cluster", "db", "pgsql"]
    extends:
      file: db/greenplum.yml
      service: greenplum
    networks:
      - backend

  redis:
    profiles: ["cluster"]
    ports:
      - 6379:6379
    extends:
      file: redis/redis.yml
      service: redis
    networks:
      - backend

  airflow-scheduler:
    profiles: ["cluster"]
    extends:
      file: airflow/airflow.yml
      service: airflow-scheduler
    networks:
      - backend

  airflow-triggrer:
    profiles: ["cluster"]
    extends:
      file: airflow/airflow.yml
      service: airflow-triggrer
    networks:
      - backend

  airflow-webserver:
    profiles: ["cluster"]
    extends:
      file: airflow/airflow.yml
      service: airflow-webserver
    networks:
      - backend

  airflow-cel-worker-1:
    profiles: ["cluster", "worker"]
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==rain3"
    extends:
      file: airflow/airflow.yml
      service: airflow-cel-worker-1
    networks:
      - backend

  airflow-cel-worker-2:
    profiles: ["cluster", "worker"]
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==rain2"
    extends:
      file: airflow/airflow.yml
      service: airflow-cel-worker-1
    networks:
      - backend

  airflow-cel-worker-3:
    profiles: ["cluster", "worker"]
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==rain"
    extends:
      file: airflow/airflow.yml
      service: airflow-cel-worker-1
    networks:
      - backend

  airflow-cel-flower:
    profiles: ["cluster"]
    extends:
      file: airflow/airflow.yml
      service: airflow-cel-flower
    networks:
      - backend

  airflow-init: 
    profiles: ["cluster"]
    extends:
      file: airflow/airflow.yml
      service: airflow-init
    networks:
      - backend

networks:
    backend:
     driver: overlay
     attachable: true
     ipam:
       config:
         - subnet: 10.10.10.0/24