version: '3.9'
x-airflow:
  &airflow-main
  build:
   context: .
  environment:
  #&airflow-env
   AIRFLOW__CORE__EXECUTOR: CeleryExecutor
   AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql://${MUSER}:${MPASS}@mysql-server/${MDB}
   # For backward compatibility, with Airflow <2.3
   AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://${MUSER}:${MPASS}@mysql-server/${MDB}
   AIRFLOW__CELERY__RESULT_BACKEND: db+mysql://${MUSER}:${MPASS}@mysql-server/${MDB}
   AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
   AIRFLOW__CORE__FERNET_KEY: ''
   AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
   AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
   AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
   #AIRFLOW_CONFIG: "/etc/airflow/airflow.cfg"
   AIRFLOW_HOME: "/airflow"
  volumes:
   - ./dags:/airflow/dags
   - ./logs:/airflow/logs
   - ./plugins:/airflow/plugins
  depends_on: 
 # &airflow-dep
   redis:
    condition: service_healthy
   mysql-server:
    condition: service_healthy

services:
  mysql-server:
   image: mysql:5.7
   hostname: mysql-server
   environment:
    MYSQL_DATABASE: "${MDB}"
    MYSQL_USER: "${MUSER}"
    MYSQL_PASSWORD: "${MPASS}"
    MYSQL_ROOT_PASSWORD: "${MROOT}"
   ports:
    - '3306:3306'
   mem_limit: 1024m
   container_name: mysql-server
   cpus: 1
   command: --connect-timeout=120 --explicit-defaults-for-timestamp=ON --max-allowed-packet=1G --wait-timeout=86400 --interactive-timeout=86400
   expose:
    - '3306'
   volumes:
    - ./data/mysql:/var/lib/mysql
   restart: always
   healthcheck:
    test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
    timeout: 20s
    retries: 10

  redis:
   image: redis
   restart: always
   hostname: redis
   container_name: redis
   mem_limit: 512m
   cpus: 1
   healthcheck:
    test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    timeout: 20s
    retries: 10

  airflow-init: 
   <<: *airflow-main
   container_name: airflow
   hostname: airflow
   entrypoint: /bin/bash
   command:
     - c
     - |
     export;
     pwd;