version: '3.9'
services:

  redis:
   image: redis
   restart: always
   hostname: redis
   container_name: redis
   expose:
    - 6379
   mem_limit: 512m
   cpus: 1
   healthcheck:
    test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    timeout: 20s
    retries: 10
